### ISSUE TITLE
Not found player info

### ISSUE THREAD

**Issue by Critzie** [Elysia-ff/FFXIV_RotationHelper#1]
Not found player info when pasting in the http://ffxivrotations.com/####
please restart act I did but nothing helped, I did do it incorrectly 
FFXIV_RotationHelper.dll into the act folder and then Plugins -> Plugin Listing -> Browse... -> Select FFXIV_RotationHelper.dll -> Add/Enabled Plugin

**Comment by Elysia-ff** [comment]
Can you show me the latest log file created before you loaded the plugin?

You can find log file location in the ACT
Plugins -> FFXIV Settings -> Log file Location -> Open FFXIV Log folder.

**Comment by Critzie** [comment]
[Network_20190430.zip](https://github.com/Elysia-ff/FFXIV_RotationHelper/files/3132449/Network_20190430.zip)

**Comment by Elysia-ff** [comment]
This plugin load your player name and id from below line of the log.
`02|2019-04-30T03:57:09.0660000+02:00|106be569|Jack Mirakuru|`

Also, these are when the line is read.
1. launching the ACT. _(The plugin must be loaded before)_
2. casting teleport. _(of course, the ACT is launched and the plugin is loaded)_

So, umm.. If the plugin is successfully loaded when the log file you gave me is being written, the plugin should've worked.

There are some solutions.
1. Make sure the plugin status is "Plugin Started" instead of "No Status".
2. Are you using ACTWeb Socket? Check Plugins -> ACTWeb Socket ->Message Filter -> BeforeLogLineRead is checked.

Is there some error when you load the plugin?
If you didn't see any error message, you can find ACT's log file below.
`%appdata%\Advanced Combat Tracker\Advanced Combat Tracker.log`

**Comment by Critzie** [comment]
Where can i find the Plugin started area and i see no actweb socket anywhere

**Comment by Elysia-ff** [comment]
![image](https://user-images.githubusercontent.com/45890606/57008626-5744d380-6c2c-11e9-9728-43247a5ca4a0.png)

It's here, ACTWeb Socket too.
If you don't use dps meter, ACTWeb Socket won't be there. and that's no matter.

**Comment by Critzie** [comment]
Yea i dont have the ACTWeb Socket, so do i need to download it if so where and how?
![chrome_PoVOF8Mpya](https://user-images.githubusercontent.com/50128318/57008704-36f82300-6bf2-11e9-86f4-64ccae4b70a6.png)

**Comment by Elysia-ff** [comment]
No, you don't need download it. and the problem was the plugin works when another plugin read the log file.

I'm gonna release new version soon. (take a few time)

**Comment by Critzie** [comment]
So it's not my fault, its an issue with the plugin, right?
Thanks a lot for looking into it and I hope the new release is going to fix it :)

**Comment by Elysia-ff** [comment]
Yep. That was my fault. I was using this plugin with others, I couldn't find the problem.
And then.. I found a solution without new release.

Just Disable FFXIV_ACT_Plugin.dll and Re-Enable it. It should work.

**Comment by Critzie** [comment]
It worked thanks :)
