### ISSUE TITLE
Request for Icon Limit.

### ISSUE THREAD

**Issue by l3uGsY** [Elysia-ff/FFXIV_RotationHelper#17]
Just a request for an option to set spell queue limit or toggle between two options, short queue (3 spells) and long queue (your default)

As well, I noticed a previous ticket of wont fix for full screen support. [LMeter](https://github.com/lichie567/LMeter) did this through ACT, if that's something you were interested in.  

Regardless, thank you for this, great way to burn a few hours working on that muscle memory.

**Comment by Elysia-ff** [comment]
What exactly dose spell queue limit mean?
If you mean spell list is too long horizontally, I think I can make it resizable with mouse dragging.

Thanks for using my plugin, and a reference for fullscreen support :)

**Comment by l3uGsY** [comment]
What exactly dose spell queue limit mean?
>>>>>> Yes, reducing the amount of icons on screen.  Your solution should work well.

If an option can be added to hide RotationHelper while the weapon in sheathed, it would provide an elegant addition to this helpful tool.
Thank you.

**Comment by Elysia-ff** [comment]
It is now resizable. see [the latest release](https://github.com/Elysia-ff/FFXIV_RotationHelper/releases/latest).

1. for full-screen support, I have to redraw the whole gui using imgui rather than WinForms, so it still won't be fixed. 😂
2. ACT does not know if you weapon is sheathed, the option you mentioned seems to be hard.

Thanks!
